# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-09 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoupload',
            field=models.FileField(upload_to='haha/media'),
        ),
    ]
