# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-09 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_auto_20200109_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoupload',
            field=models.FileField(upload_to='static/media/'),
        ),
    ]
